import React from 'react';
import { Image as ImageIcon, Table2, FileText, BarChart2, Download } from 'lucide-react';
import { useApp } from '../../../context/AppContext';
import { seleneApi } from '../../../services/api';

export const ExportsView: React.FC = () => {
  const { addLog, addToast, results, isComplete } = useApp();

  const jobId = results.jobId;
  const isReal = isComplete && jobId && !jobId.startsWith('demo_');

  const handleDownload = (productPath: string | undefined, filename: string) => {
    if (isReal && productPath) {
      const url = seleneApi.productUrl(productPath);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.target = '_blank';
      a.click();
      addLog(`Downloading ${filename} from backend…`, 'success');
      addToast(`Downloading ${filename} from the server.`, 'success', 'Download Started');
    } else {
      let content = '';
      let mimeType = 'text/plain';

      if (filename.endsWith('.csv')) {
        content =
          'source_x,source_y,reference_x,reference_y,inlier,confidence\n120.2,88.4,121.0,88.9,1,0.98\n240.5,156.2,241.1,155.7,1,0.96\n';
        mimeType = 'text/csv';
      } else if (filename.endsWith('.pdf')) {
        content =
          'SELENE-MATCH registration report\nRMSE: 0.68 px\nInlier Ratio: 87.6%\nCE90: 0.91 px\nNNI: 0.84\nGrid Coverage: 81%\n';
        mimeType = 'application/pdf';
      } else {
        content =
          'SELENE-MATCH simulated registered GeoTIFF placeholder. Upload real images and run the pipeline for live raster export.';
      }

      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
      addLog(`Prepared demo download: ${filename}`, 'success');
      addToast(`${filename} (demo placeholder) downloaded.`, 'info', 'Demo Download');
    }
  };

  const exports = [
    {
      icon: <ImageIcon className="w-6 h-6 text-cyan-400" />,
      borderColor: 'rgba(111,246,255,0.3)',
      bgColor: 'rgba(57,168,255,0.1)',
      filename: 'registered.tif',
      label: 'DOWNLOAD GEOTIFF',
      description: 'Registered GeoTIFF / final raster product.',
      productPath: isReal ? `/products/${jobId}/registered.tif` : undefined,
    },
    {
      icon: <Table2 className="w-6 h-6 text-emerald-400" />,
      borderColor: 'rgba(62,230,160,0.3)',
      bgColor: 'rgba(62,230,160,0.1)',
      filename: 'matches.csv',
      label: 'DOWNLOAD CSV',
      description: 'Correspondence and GCP records.',
      productPath: isReal ? `/products/${jobId}/matches.csv` : undefined,
    },
    {
      icon: <FileText className="w-6 h-6 text-amber-400" />,
      borderColor: 'rgba(255,182,92,0.3)',
      bgColor: 'rgba(255,182,92,0.1)',
      filename: 'registration_report.pdf',
      label: 'DOWNLOAD REPORT',
      description: 'One-page summary with metadata, metrics and visual proof.',
      productPath: isReal ? `/products/${jobId}/registration_report.pdf` : undefined,
    },
    {
      icon: <BarChart2 className="w-6 h-6 text-amber-400" />,
      borderColor: 'rgba(255,182,92,0.3)',
      bgColor: 'rgba(255,182,92,0.1)',
      filename: 'plot_checkerboard.png',
      label: 'CHECKERBOARD',
      description: 'Checkerboard overlay verification plot.',
      productPath: isReal ? `/products/${jobId}/plot_checkerboard.png` : undefined,
    },
  ];

  return (
    <section id="view-exports" className="view-section active space-y-6">
      {/* PAGE HEADER */}
      <div className="flex items-center gap-3 flex-wrap pb-1">
        <h1 className="text-2xl font-bold font-display text-white tracking-wide">
          Exports
        </h1>
        {isReal ? (
          <span className="badge font-mono text-[10.5px] tracking-[0.14em] font-semibold text-emerald-400 bg-emerald-950/40 border border-emerald-500/30 px-3 py-1 rounded-md">
            LIVE · JOB {jobId}
          </span>
        ) : (
          <span className="badge font-mono text-[10.5px] tracking-[0.14em] font-semibold text-amber-400 bg-amber-950/40 border border-amber-500/30 px-3 py-1 rounded-md">
            DEMO MODE
          </span>
        )}
        <div className="screen-subtitle w-full text-[12.5px] text-slate-400 font-mono tracking-wide mt-1">
          Download the tangible products generated by a registration job.
          {!isReal && (
            <span className="ml-2 text-amber-400 font-medium">
              Run the pipeline with real images to download live outputs.
            </span>
          )}
        </div>
      </div>

      {/* EXPORTS CARDS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6">
        {exports.map((exp) => (
          <div key={exp.filename} className="card bracket p-6 sm:p-7 rounded-xl bg-slate-950/60 border border-[rgba(146,196,255,0.14)] backdrop-blur-md flex flex-col justify-between group hover:border-[rgba(146,196,255,0.3)] transition-all">
            <div>
              <div
                className="w-12 h-12 rounded-xl flex items-center justify-center mb-5 border shadow-lg"
                style={{ borderColor: exp.borderColor, background: exp.bgColor }}
              >
                {exp.icon}
              </div>
              <h3 className="text-white font-mono text-[14px] font-bold tracking-wide">{exp.filename}</h3>
              <p className="text-[11.5px] text-slate-400 font-mono mt-2 leading-relaxed">{exp.description}</p>
            </div>
            <button
              onClick={() => handleDownload(exp.productPath, exp.filename)}
              className="px-4 py-3 mt-6 rounded-lg text-[11.5px] font-bold font-display tracking-[0.12em] border border-cyan-400/40 text-cyan-300 bg-cyan-950/30 hover:bg-cyan-950/60 flex items-center justify-center gap-2 transition-all cursor-pointer shadow-[0_0_12px_rgba(111,246,255,0.15)]"
            >
              <Download className="w-4 h-4 text-cyan-400" />
              {exp.label}
            </button>
          </div>
        ))}
      </div>

      {/* RUN PACKAGE TERMINAL PANEL */}
      <div className="card p-6 sm:p-7 rounded-xl bg-slate-950/60 border border-[rgba(146,196,255,0.14)] backdrop-blur-md">
        <h3 className="text-[14px] font-bold font-display text-white tracking-wide uppercase">
          RUN PACKAGE STRUCTURE
        </h3>
        <div className="term mt-4 p-5 rounded-xl border border-[rgba(146,196,255,0.14)] bg-[#040910] font-mono text-[11.5px] text-slate-300 leading-relaxed space-y-1">
          <div className="text-cyan-400 font-bold mb-2">products/{isReal ? jobId : 'job_xxxxxxxx'}/</div>
          <div className="text-slate-400">├── registered.tif</div>
          <div className="text-slate-400">├── matches.csv</div>
          <div className="text-slate-400">├── plot_checkerboard.png</div>
          <div className="text-slate-400">├── plot_quiver.png</div>
          <div className="text-slate-400">├── plot_coverage.png</div>
          <div className="text-slate-400">└── registration_report.pdf</div>
        </div>
      </div>
    </section>
  );
};

