import React from 'react';
import { Image as ImageIcon, Table2, FileText } from 'lucide-react';
import { useApp } from '../../../context/AppContext';

export const ExportsView: React.FC = () => {
  const { addLog, addToast } = useApp();

  const handleDownload = (filename: string) => {
    let content = '';
    let mimeType = 'text/plain';

    if (filename.endsWith('.csv')) {
      content =
        'source_x,source_y,reference_x,reference_y,inlier,confidence\n120.2,88.4,121.0,88.9,1,0.98\n240.5,156.2,241.1,155.7,1,0.96\n';
      mimeType = 'text/csv';
    } else if (filename.endsWith('.pdf')) {
      content =
        'SELENE-MATCH registration report\nRMSE: 0.68 px\nInlier Ratio: 87.6%\nCE90: 0.91 px\nNNI: 0.84\nGrid Coverage: 81%\n';
      mimeType = 'application/pdf';
    } else {
      content =
        'SELENE-MATCH simulated registered GeoTIFF placeholder. Connect FastAPI/GDAL backend for live raster export.';
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);

    addLog(`Prepared download: ${filename}`, 'success');
    addToast(`${filename} has been prepared for download.`, 'success', 'Download Ready');
  };

  return (
    <section id="view-exports" className="view-section active">
      <div className="mb-5">
        <div className="screen-title">Exports</div>
        <div className="screen-subtitle">
          Download the tangible products generated by a registration job.
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* GEOTIFF */}
        <div className="card bracket p-5 group">
          <div className="w-10 h-10 rounded-xl border border-[rgba(111,246,255,0.25)] bg-[rgba(57,168,255,0.07)] flex items-center justify-center mb-4">
            <ImageIcon className="w-5 h-5 text-brand-400" />
          </div>
          <h3 className="text-white font-mono text-[12.5px] tracking-wide">
            registered.tif
          </h3>
          <p className="text-[11px] text-slate-500 mt-1.5 leading-relaxed">
            Registered GeoTIFF / final raster product.
          </p>
          <button
            onClick={() => handleDownload('registered.tif')}
            className="btn-secondary w-full mt-5 py-2.5 rounded-lg text-[10px] tracking-[0.1em] font-mono"
          >
            ↓ DOWNLOAD GEOTIFF
          </button>
        </div>

        {/* CSV */}
        <div className="card bracket p-5 group">
          <div className="w-10 h-10 rounded-xl border border-[rgba(62,230,160,0.25)] bg-[rgba(62,230,160,0.06)] flex items-center justify-center mb-4">
            <Table2 className="w-5 h-5 text-success" />
          </div>
          <h3 className="text-white font-mono text-[12.5px] tracking-wide">
            matches.csv
          </h3>
          <p className="text-[11px] text-slate-500 mt-1.5 leading-relaxed">
            Correspondence and GCP records.
          </p>
          <button
            onClick={() => handleDownload('matches.csv')}
            className="btn-secondary w-full mt-5 py-2.5 rounded-lg text-[10px] tracking-[0.1em] font-mono"
          >
            ↓ DOWNLOAD CSV
          </button>
        </div>

        {/* REPORT */}
        <div className="card bracket p-5 group">
          <div className="w-10 h-10 rounded-xl border border-[rgba(255,182,92,0.25)] bg-[rgba(255,182,92,0.06)] flex items-center justify-center mb-4">
            <FileText className="w-5 h-5 text-warning" />
          </div>
          <h3 className="text-white font-mono text-[12.5px] tracking-wide">
            registration_report.pdf
          </h3>
          <p className="text-[11px] text-slate-500 mt-1.5 leading-relaxed">
            One-page summary with metadata, metrics and visual proof.
          </p>
          <button
            onClick={() => handleDownload('registration_report.pdf')}
            className="btn-secondary w-full mt-5 py-2.5 rounded-lg text-[10px] tracking-[0.1em] font-mono"
          >
            ↓ DOWNLOAD REPORT
          </button>
        </div>
      </div>

      <div className="card p-5 mt-5">
        <h3 className="text-[13px] font-semibold text-white tracking-wide">
          RUN PACKAGE
        </h3>
        <div className="term mt-3 p-4 font-mono text-[10px] text-slate-400 leading-[1.9]">
          <div className="text-brand-300">products/job1/</div>
          <div>├── registered.tif</div>
          <div>├── matches.csv</div>
          <div>├── checkerboard_overlay.png</div>
          <div>├── residual_quiver.png</div>
          <div>├── gcp_density.png</div>
          <div>└── registration_report.pdf</div>
        </div>
      </div>
    </section>
  );
};
